
train_iterations : 1000
horizon_length : 15
batch_size : 32
batch_length : 50
collect_interval : 100
num_interaction_episodes : 1
seed_episodes : 5
epochs: 10
num_evaluate : 3
env_name: "l2rpn_case14_sandbox"
episode_num : 100000
latent_dim : 64
hidden_dim : 128
actor_hidden_dims : [384, 768, 1536, 768, 384]
hidden_layers : 3
input_dim : 467
action_dim : 179
device : 'cuda'
learning_rate : 1e-4
free_bits_threshold : 1e-6
kl_weight : 1e-2
path : "dreamer\\models"
saved_model_path : "dreamer\\models"
pre_trained_path : "dreamer\\Pre_trained_models\\models"
horizon :  16 
gamma : 0.997
lambda_gae : 0.95
entropy_scale : 0.0003
critic_ema_decay : 0.995
num_buckets : 255
actor_epsilon : 0.003
actor_critic_lr : 0.0003